"""OpenRouter AI client.

This module provides a centralised interface for communicating with
OpenRouter. Other parts of the application should use this client
instead of making direct HTTP requests to OpenRouter.
"""

import httpx

from app.config import settings


class AIClientError(Exception):
    """Represent an error communicating with the AI provider."""


async def chat_completion(
    system_prompt: str,
    user_prompt: str,
) -> str:
    """Send a chat completion request to OpenRouter.

    Args:
        system_prompt: Instructions describing the AI's role.
        user_prompt: The user's request.

    Returns:
        The text generated by the AI model.

    Raises:
        AIClientError: If the API key is missing or the request fails.
    """

    if not settings.OPENROUTER_API_KEY:
        raise AIClientError(
            "OPENROUTER_API_KEY is not configured."
        )

    headers = {
        "Authorization": f"Bearer {settings.OPENROUTER_API_KEY}",
        "Content-Type": "application/json",
    }

    payload = {
        "model": settings.OPENROUTER_MODEL,
        "messages": [
            {
                "role": "system",
                "content": system_prompt,
            },
            {
                "role": "user",
                "content": user_prompt,
            },
        ],
    }

    try:
        async with httpx.AsyncClient(timeout=60.0) as client:
            response = await client.post(
                settings.OPENROUTER_URL,
                headers=headers,
                json=payload,
            )

        response.raise_for_status()

        data = response.json()

        return data["choices"][0]["message"]["content"]

    except (httpx.HTTPError, KeyError, IndexError) as exc:
        raise AIClientError(
            "The AI provider request failed."
        ) from exc